---
name: performance-testing
on:
  push:
    branches:
    - 'release/**'
jobs:
  ### INTERDOMAIN CLUSTER
  interdomain-kind:
    runs-on: ubuntu-latest
    env:
      KUBERNETES_VERSION: ${{ secrets.NSM_KUBERNETES_VERSION }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16
        github-token: ${{ github.token }}
    - name: Set go env
      run: |
        echo GOPATH=$GITHUB_WORKSPACE >> $GITHUB_ENV
        echo GO111MODULE=on >> $GITHUB_ENV
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
    - uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    - name: Get kind
      run: go get sigs.k8s.io/kind@v0.11.1
    - name: Create kind clusters
      run: |
        if [[ $KUBERNETES_VERSION=="" ]]; then
            KUBERNETES_VERSION="v1.22.1"
        fi
        for (( i = 1; i <= 2; i++ )); do
            kind create cluster --name "kind-${i}" --config cluster-config-interdomain.yaml --image="kindest/node:$KUBERNETES_VERSION"
            configPath=${{ github.workspace }}/src/github.com/${{ github.repository }}/config${i}
            kind get kubeconfig --name "kind-${i}" > ${configPath}
            echo KUBECONFIG${i}=${configPath} >> $GITHUB_ENV
            echo CLUSTER${i}_CIDR="172.18.${i}.128/25" >> $GITHUB_ENV
        done
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    - name: Install gotestmd
      run: |
        ./performance_testing/scripts/generate-install.sh
    - name: Clone deployments-k8s
      run: |
        cd ..
        git clone --depth=1 https://github.com/networkservicemesh/deployments-k8s.git || exit
        cd deployments-k8s
        git fetch origin tag "$NSM_VERSION" --no-tags --depth=1 || exit
        git checkout "$NSM_VERSION" || exit
      env:
        NSM_VERSION: ${{ github.ref_name }}
    - name: Generate setup scripts
      run: |
        ./performance_testing/scripts/generate-scripts.sh ../deployments-k8s
    - name: Performance tests
      run: |
        performance_testing/scripts/full_ci_run.sh "$NSM_VERSION" "$ARTIFACTS_DIR" "$QPS_LIST" "$DURATION" "$CONNECTIONS" "$ITERATIONS" "$DEPLOYMENTS_LOCATIONS"
      env:
        NSM_VERSION: ${{ github.ref_name }}
        ARTIFACTS_DIR: perf-test-results
        QPS_LIST: 100 1000 1000000
        DURATION: 60s
        CONNECTIONS: 1
        ITERATIONS: 3
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    - name: Print results
      run: |
        performance_testing/scripts/print_all_summaries.sh "$ARTIFACTS_DIR"
      env:
        ARTIFACTS_DIR: perf-test-results
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    - name: Cleanup resources
      if: ${{ success() || failure() || cancelled() }}
      run: kind delete clusters $(kind get clusters)
    - name: Upload artifacts
      if: ${{ success() || failure() || cancelled() }}
      uses: actions/upload-artifact@v2
      with:
        name: Performance tests results and logs
        path: ${{ github.workspace }}/src/github.com/${{ github.repository }}/perf-test-results
